disposition:
    pattern:  /disposition
    defaults: { _controller: ExtranetDispositionBundle:Disposition:index }

disposition_new:
    pattern:  /disposition/new
    defaults: { _controller: ExtranetDispositionBundle:Disposition:new }

disposition_create:
    pattern:  /disposition/create
    defaults: { _controller: ExtranetDispositionBundle:Disposition:create }

disposition_show:
    pattern:  /disposition/{id}
    defaults: { _controller: ExtranetDispositionBundle:PdfMail:generateDisposition }

disposition_delete:
    pattern:  /disposition/delete/{id}
    defaults: { _controller: ExtranetDispositionBundle:Disposition:delete }

disposition_update:
    pattern:  /disposition/update/{id}
    defaults: { _controller: ExtranetDispositionBundle:Disposition:update }

disposition_edit:
    pattern:  /disposition/{id}/edit
    defaults: { _controller: ExtranetDispositionBundle:Disposition:edit }

generate_disposition:
    pattern:  /generate/disposition/{id}
    defaults: { _controller: ExtranetDispositionBundle:PdfMail:generateDisposition }

mail_disposition:
    pattern:  /mail/disposition/{id}
    defaults: { _controller: ExtranetDispositionBundle:PdfMail:mailDisposition }

download_disposition:
    pattern:  /download/disposition/{id}
    defaults: { _controller: ExtranetDispositionBundle:PdfMail:downloadDisposition }

add_disposition:
    pattern:  /add/disposition
    defaults: { _controller: ExtranetDispositionBundle:PdfMail:addDisposition }

wkdate:
    pattern:  /wkdate
    defaults: { _controller: ExtranetDispositionBundle:Wkdate:index }

wkdate_new:
    pattern:  /wkdate/new
    defaults: { _controller: ExtranetDispositionBundle:Wkdate:new }

wkdate_create:
    pattern:  /wkdate/create
    defaults: { _controller: ExtranetDispositionBundle:Wkdate:create }

wkdate_show:
    pattern:  /wkdate/{id}
    defaults: { _controller: ExtranetDispositionBundle:Wkdate:show }

wkdate_delete:
    pattern:  /wkdate/delete/{id}
    defaults: { _controller: ExtranetDispositionBundle:Wkdate:delete }

wkdate_update:
    pattern:  /wkdate/update/{id}
    defaults: { _controller: ExtranetDispositionBundle:Wkdate:update }

wkdate_edit:
    pattern:  /wkdate/{id}/edit
    defaults: { _controller: ExtranetDispositionBundle:Wkdate:edit }