personnel:
    pattern:  /personnel
    defaults: { _controller: ExtranetPersonnelBundle:Personnel:index }

personnel_new:
    pattern:  /personnel/new
    defaults: { _controller: ExtranetPersonnelBundle:Personnel:new }

personnel_create:
    pattern:  /personnel/create
    defaults: { _controller: ExtranetPersonnelBundle:Personnel:create }

personnel_show:
    pattern:  /personnel/{id}
    defaults: { _controller: ExtranetPersonnelBundle:Personnel:show }

personnel_delete:
    pattern:  /personnel/delete/{id}
    defaults: { _controller: ExtranetPersonnelBundle:Personnel:delete }

personnel_update:
    pattern:  /personnel/update/{id}
    defaults: { _controller: ExtranetPersonnelBundle:Personnel:update }

personnel_edit:
    pattern:  /personnel/{id}/edit
    defaults: { _controller: ExtranetPersonnelBundle:Personnel:edit }


qualification:
    pattern:  /qualification
    defaults: { _controller: ExtranetPersonnelBundle:Qualification:index }

qualification_new:
    pattern:  /qualification/new
    defaults: { _controller: ExtranetPersonnelBundle:Qualification:new }

qualification_create:
    pattern:  /qualification/create
    defaults: { _controller: ExtranetPersonnelBundle:Qualification:create }

qualification_show:
    pattern:  /qualification/{id}
    defaults: { _controller: ExtranetPersonnelBundle:Qualification:show }

qualification_delete:
    pattern:  /qualification/delete/{id}
    defaults: { _controller: ExtranetPersonnelBundle:Qualification:delete }

qualification_update:
    pattern:  /qualification/update/{id}
    defaults: { _controller: ExtranetPersonnelBundle:Qualification:update }

qualification_edit:
    pattern:  /qualification/{id}/edit
    defaults: { _controller: ExtranetPersonnelBundle:Qualification:edit }
