divers:
    pattern: /divers
    defaults: { _controller: ExtranetDiversBundle:Divers:index }


entete:
    pattern:  /entete
    defaults: { _controller: ExtranetDiversBundle:Entete:index }

entete_new:
    pattern:  /entete/new
    defaults: { _controller: ExtranetDiversBundle:Entete:new }

entete_create:
    pattern:  /entete/create
    defaults: { _controller: ExtranetDiversBundle:Entete:create }

entete_show:
    pattern:  /entete/{id}
    defaults: { _controller: ExtranetDiversBundle:Entete:show }

entete_delete:
    pattern:  /entete/delete/{id}
    defaults: { _controller: ExtranetDiversBundle:Entete:delete }

entete_update:
    pattern:  /entete/update/{id}
    defaults: { _controller: ExtranetDiversBundle:Entete:update }

entete_edit:
    pattern:  /entete/{id}/edit
    defaults: { _controller: ExtranetDiversBundle:Entete:edit }



pied:
    pattern:  /pied
    defaults: { _controller: ExtranetDiversBundle:Pied:index }

pied_new:
    pattern:  /pied/new
    defaults: { _controller: ExtranetDiversBundle:Pied:new }

pied_create:
    pattern:  /pied/create
    defaults: { _controller: ExtranetDiversBundle:Pied:create }

pied_show:
    pattern:  /pied/{id}
    defaults: { _controller: ExtranetDiversBundle:Pied:show }

pied_delete:
    pattern:  /pied/delete/{id}
    defaults: { _controller: ExtranetDiversBundle:Pied:delete }

pied_update:
    pattern:  /pied/update/{id}
    defaults: { _controller: ExtranetDiversBundle:Pied:update }

pied_edit:
    pattern:  /pied/{id}/edit
    defaults: { _controller: ExtranetDiversBundle:Pied:edit }




conditions:
    pattern:  /conditions
    defaults: { _controller: ExtranetDiversBundle:Conditions:index }

conditions_new:
    pattern:  /conditions/new
    defaults: { _controller: ExtranetDiversBundle:Conditions:new }

conditions_create:
    pattern:  /conditions/create
    defaults: { _controller: ExtranetDiversBundle:Conditions:create }

conditions_show:
    pattern:  /conditions/{id}
    defaults: { _controller: ExtranetDiversBundle:Conditions:show }

conditions_delete:
    pattern:  /conditions/delete/{id}
    defaults: { _controller: ExtranetDiversBundle:Conditions:delete }

conditions_update:
    pattern:  /conditions/update/{id}
    defaults: { _controller: ExtranetDiversBundle:Conditions:update }

conditions_edit:
    pattern:  /conditions/{id}/edit
    defaults: { _controller: ExtranetDiversBundle:Conditions:edit }





taux:
    pattern:  /taux
    defaults: { _controller: ExtranetDiversBundle:Taux:index }

taux_new:
    pattern:  /taux/new
    defaults: { _controller: ExtranetDiversBundle:Taux:new }

taux_create:
    pattern:  /taux/create
    defaults: { _controller: ExtranetDiversBundle:Taux:create }

taux_show:
    pattern:  /taux/{id}
    defaults: { _controller: ExtranetDiversBundle:Taux:show }

taux_delete:
    pattern:  /taux/delete/{id}
    defaults: { _controller: ExtranetDiversBundle:Taux:delete }

taux_update:
    pattern:  /taux/update/{id}
    defaults: { _controller: ExtranetDiversBundle:Taux:update }

taux_edit:
    pattern:  /taux/{id}/edit
    defaults: { _controller: ExtranetDiversBundle:Taux:edit }
