extranet_disposition:
    resource: "@ExtranetDispositionBundle/Resources/config/routing.yml"
    prefix:   /

extranet_user:
    resource: "@ExtranetUserBundle/Resources/config/routing.yml"
    prefix:   /

extranet_docs:
    resource: "@ExtranetDocsBundle/Resources/config/routing.yml"
    prefix:   /

extranet_divers:
    resource: "@ExtranetDiversBundle/Resources/config/routing.yml"
    prefix:   /

extranet_utilisateur:
    resource: "@ExtranetUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

extranet_personnel:
    resource: "@ExtranetPersonnelBundle/Resources/config/routing.yml"
    prefix:   /

extranet_app:
    resource: "@ExtranetAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile