<?php

namespace Extranet\DispositionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WkdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WkdateRepository extends EntityRepository
{
}
