parameters:
#    extranet_personnel.example.class: Extranet\PersonnelBundle\Example

services:
#    extranet_personnel.example:
#        class: %extranet_personnel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
