<?php

namespace Extranet\DiversBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConditionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionsRepository extends EntityRepository
{
}
